### ISSUE TITLE
Wrong Creds

### ISSUE THREAD

**Issue by parteeksingh005** [Anon-Exploiter/ine-dl#1]
I am trying to check if your script works. I have followed the instructions. Wen i run the script it's showing me **ERROR Wrong credentials specified!**.  Can you help me with this why i am getting this error? 

![Eror](https://user-images.githubusercontent.com/39644332/180602256-bebf6375-424b-4caf-9778-090e4445415e.png)

**Comment by Anon-Exploiter** [comment]
Hi, 

Just to be sure, are you able to login into the web application with the same credentials? Does your password contain a backslash `\`? That could escape the JSON double-quotes and might be the issue here.

**Comment by parteeksingh005** [comment]
HI,
I am able to login into the web application with the same credentials. No, Password doesn't contain any backslash.
Instead, I am logging in by using **log in with Google**. Is there any chance using the different login mechanism the script is not recognizing the credentials?

**Comment by Anon-Exploiter** [comment]
Sorry, the script won't work with those credentials. 

I've seen the option for signing in with Google and other OAuth providers but since I can't publicly signup with them, I can't write a module for it in the script. 

If you want to, I can take a look at how the authentication is happening using your credentials. Let me know if you're up for it.

**Comment by Anon-Exploiter** [comment]
Closing due to no response
